services:
  - type: web
    name: fastapi-app
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "./start.sh"
    envVars:
      - key: PORT
        value: 10000